// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktxclksljhjuuyzhjnub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0eGNsa3NsamhqdXV5emhqbnViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NzIwMzQsImV4cCI6MjA2MjU0ODAzNH0.7IE_IEw8z9aTqWuNu4j5og0lo3CN9o2kjplhs0noILY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);